### ISSUE TITLE
In verbose mode uploaded file names disappear

### ISSUE THREAD

**Issue by utgarda** [solutious/rudy#44]
Yeah, and can't be logged properly, for that matter

```
upload_provisioning do #upload to ~root
  remote do
    file_upload 'provisioning/cloud_demos.conf'
    dir_upload 'provisioning/app-keys'
    dir_upload 'provisioning/ec2-keys'
    disable_safe_mode
    file_upload 'provisioning/*.sh'
  end
end
```

When run, that shows uploading progress, but doesn't leave it on the screen :

```
> rudy -vvv  upload_provisioning
Loading config from /home/etsvigun/.rudy/config
Loading config from /home/etsvigun/devenv/CloudDemos/Rudyfile
RUDY v0.9.8.001 -- Griddynamics Consulting -- 2010-05-18 14:28:34 UTC
[R:eu-west-1  z:eu-west-1a  e:stash  r:stash]

 Executing routine: upload_provisioning 

upload to: /root

upload to: /root

upload to: /root

upload to: /root

The following machines were processed:
m-eu-west-1a-stash-stash-01; i-86cf4df1; ec2-79-125-47-70.eu-west-1.compute.amazonaws.com
```

Elapsed: 13.73 seconds

**Comment by delano** [comment]
Good catch! I'll fix it in the next release.

**Comment by delano** [comment]
I fixed this in rye for now, the 0.8.16 release. 

```
sudo gem install rye
```

**Comment by utgarda** [comment]
Yep, now single files are properly listed. But is it ok that upload_dir shows progress for every single file uploaded, and then all is left is something like this?
    upload to: /root
    [upload] provisioning/app-keys /root

**Comment by delano** [comment]
That would be the ideal solution, but I had off the directory path to Net::SCP so it's not a straightforward solution. The current solution is good enough for now (and there are probably more important problems to be fixed). 

Thanks again for the reporting this one. The fix actually helped me today as well!
