### ISSUE TITLE
Rudy doesn't work with Ruby 1.8.5

### ISSUE THREAD

**Issue by utgarda** [solutious/rudy#45]
```
# gem install rudy
Successfully installed rudy-0.9.8.005
1 gem installed
Installing ri documentation for rudy-0.9.8.005...
Installing RDoc documentation for rudy-0.9.8.005...
# rudy --version
ERROR (ArgumentError): wrong number of arguments (1 for 2)
```

That's sad. The only output from any rudy call.

```
# uname -a
Linux m-eu-west-1a-stash-stash-01 2.6.21.7-2.fc8xen #1 SMP Fri Feb 15 12:39:36 EST 2008 i686 i686 i386 GNU/Linux
# gem --version
1.3.3
# ruby --version
ruby 1.8.5 (2006-08-25) [i386-linux]
```

**Comment by delano** [comment]
That's no fun!

Can you send me the output of:

```
rudy --version -D
```

**Comment by utgarda** [comment]
Same output:
    # gem install rudy
    Successfully installed drydock-0.6.9
    Successfully installed storable-0.7.4
    Successfully installed sysinfo-0.7.3
    Successfully installed highline-1.5.2
    Successfully installed net-scp-1.0.2
    Successfully installed rye-0.8.17
    Successfully installed attic-0.5.2
    Successfully installed annoy-0.5.6
    Successfully installed caesars-0.7.4
    Successfully installed gibbler-0.8.3
    Successfully installed builder-2.1.2
    Successfully installed mime-types-1.16
    Successfully installed aws-s3-0.6.2
    Successfully installed amazon-ec2-0.9.14
    Successfully installed rudy-0.9.8.005
    15 gems installed
    Installing ri documentation for drydock-0.6.9...
    Installing ri documentation for storable-0.7.4...
    Installing ri documentation for sysinfo-0.7.3...
    Unrecognized directive 'vm' in README.rdoc
    Unrecognized directive 'os' in README.rdoc
    Unrecognized directive 'impl' in README.rdoc
    Unrecognized directive 'shell' in README.rdoc
    Unrecognized directive 'user' in README.rdoc
    Installing ri documentation for highline-1.5.2...
    Installing ri documentation for net-scp-1.0.2...
    Installing ri documentation for rye-0.8.17...
    Installing ri documentation for attic-0.5.2...
    Installing ri documentation for annoy-0.5.6...
    Installing ri documentation for caesars-0.7.4...
    Installing ri documentation for gibbler-0.8.3...
    Installing ri documentation for builder-2.1.2...
    ERROR:  While generating documentation for builder-2.1.2
    ... MESSAGE:   Unhandled special: Special: type=17, text=""
    ... RDOC args: --ri --op /usr/lib/ruby/gems/1.8/doc/builder-2.1.2/ri --title Builder -- Easy XML Building --main README --line-numbers --quiet lib CHANGES Rakefile README doc/releases/builder-1.2.4.rdoc doc/releases/builder-2.0.0.rdoc doc/releases/builder-2.1.1.rdoc --title builder-2.1.2 Documentation
    (continuing with the rest of the installation)
    Installing ri documentation for mime-types-1.16...
    Installing ri documentation for aws-s3-0.6.2...
    Installing ri documentation for amazon-ec2-0.9.14...
    Installing ri documentation for rudy-0.9.8.005...
    Installing RDoc documentation for drydock-0.6.9...
    Installing RDoc documentation for storable-0.7.4...
    Installing RDoc documentation for sysinfo-0.7.3...
    Unrecognized directive 'vm' in README.rdoc
    Unrecognized directive 'os' in README.rdoc
    Unrecognized directive 'impl' in README.rdoc
    Unrecognized directive 'shell' in README.rdoc
    Unrecognized directive 'user' in README.rdoc
    Installing RDoc documentation for highline-1.5.2...
    Installing RDoc documentation for net-scp-1.0.2...
    Installing RDoc documentation for rye-0.8.17...
    Installing RDoc documentation for attic-0.5.2...
    Installing RDoc documentation for annoy-0.5.6...
    Installing RDoc documentation for caesars-0.7.4...
    Installing RDoc documentation for gibbler-0.8.3...
    Installing RDoc documentation for builder-2.1.2...
    Installing RDoc documentation for mime-types-1.16...
    Installing RDoc documentation for aws-s3-0.6.2...
    Installing RDoc documentation for amazon-ec2-0.9.14...
    Installing RDoc documentation for rudy-0.9.8.005...
    # rudy --version
    ERROR (ArgumentError): wrong number of arguments (1 for 2)
    # rudy --version -D  
    ERROR (ArgumentError): wrong number of arguments (1 for 2)
    # rudy -D
    ERROR (ArgumentError): wrong number of arguments (1 for 2)
And, maybe that can help - I use  ami-55b39821, description here: http://support.rightscale.com/15-References/Tables/MultiCloud_Images_and_RightImages

The image has 'alpha' status for some reason, so maybe it's not your bug, but it'll be great if you check that. Can I get you debug info any other way?

**Comment by delano** [comment]
Hmm, I was hoping to get the stack trace. It's probably not related to the AMI. 

Is there any chance you could upgrade your Ruby to 1.8.6 or 1.8.7? I haven't been able to replicate the issue with either of those and I dont have 1.8.5 to test it out. If you're not able to upgrade let me know and I'll figure something else out!

**Comment by utgarda** [comment]
CentOS 5.4 repositories seem not to have any newer versions.
I somewhat overdid it and got the latest Ruby 1.9.1, cause it's the first source download link at ruby-lang.org.
Well, it seems to work fine. Later I'll try 1.86.

**Comment by delano** [comment]
Great, 1.9.1 is good too (I test against 1.9.1, 1.8.7, and JRuby 1.4). I'm glad that fixed it.

Don't worry about testing it 1.8.6 unless you have another reason to install it!
