### ISSUE TITLE
rudy ssh asks for password

### ISSUE THREAD

**Issue by utgarda** [solutious/rudy#47]
Using ssh with keys created with 'rudy startup' is ok :
    ssh -i ~/.ssh/key-eu-west-1a-etsvigun-admin root@ec2-79-125-76-108.eu-west-1.compute.amazonaws.com

But 'rudy ssh' doesn't seem to use them, and asks for password:
    [cloud-demos@m-eu-west-1a-stash-stash-01 etsvigun]$ rudy -D ssh
    D:  CRITERIA: {:region=>:"eu-west-1", :zone=>:"eu-west-1a", :environment=>:etsvigun, :role=>:admin, :rtype=>"m"}
    D:  SELECT: select \* from rudy_state  where region='eu-west-1' and zone='eu-west-1a' and environment='etsvigun' and role='admin' and rtype='m'
    D:  GET: m-eu-west-1a-etsvigun-admin-01
    D:  GET: m-eu-west-1a-etsvigun-admin-01
    D:  PUT: m-eu-west-1a-etsvigun-admin-01

```
 m-eu-west-1a-etsvigun-admin-01                     awsid: i-7c3bb30b 
Connecting root@ec2-79-125-76-108.eu-west-1.compute.amazonaws.com 
Password: 

[cloud-demos@m-eu-west-1a-stash-stash-01 etsvigun]$ rudy -D machines
D:  CRITERIA: {:region=>:"eu-west-1", :zone=>:"eu-west-1a", :environment=>:etsvigun, :role=>:admin, :rtype=>"m"}
D:  SELECT: select * from rudy_state  where region='eu-west-1' and zone='eu-west-1a' and environment='etsvigun' and role='admin' and rtype='m'
m-eu-west-1a-etsvigun-admin-01; i-7c3bb30b; ec2-79-125-76-108.eu-west-1.compute.amazonaws.com

[cloud-demos@m-eu-west-1a-stash-stash-01 etsvigun]$ rudy --version
Rudy version: 0.9.8.005
[cloud-demos@m-eu-west-1a-stash-stash-01 etsvigun]$ ruby --version
ruby 1.9.1p378 (2010-01-10 revision 26273) [i686-linux]
```

**Comment by delano** [comment]
I couldn't reproduce the bug, so it could be something to do with configuration. Can you send me the output of these commands:

```
$ rudy -u root -D -vvvv ssh
```

(-vvvv is super verbose mode which will also print Rye output)

```
$ ls -l ~/.ssh/key-eu-west-1a-etsvigun-admin
```

**Comment by utgarda** [comment]
Too long since I reported this one, can't reproduce it too - closing.
