### ISSUE TITLE
Commands config must be placed before Routines config

### ISSUE THREAD

**Issue by solutious** [solutious/rudy#8]
The commands config affects the way the routines config is processed. There's currently no way to force reprocessing of a single config type so Rudy has a limitation that the commands config must occur before the routines config.

This can occur in one of two ways:
- Put config in separate files (commands.rb, machines.rb, routines.rb, etc...). Commands will be loaded first.
- Put the commands config above the routines config in the same file.

**Comment by delano** [comment]
This was fixed in 0.7.1 with the change to store routines before/after/script blocks as Procs.
